name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Just for debug
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Build Condition
        id: skipper
        uses: fkirc/skip-duplicate-actions@v5
        with:
          paths_ignore: '["**/README.md", ".github/**/*.md", ".gitignore", "docs/**", "gradle.properties"]'

      - name: Checkout
        uses: actions/checkout@v4
        if: steps.skipper.outputs.should_skip != 'true'
        with:
          fetch-tags: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        if: steps.skipper.outputs.should_skip != 'true'
        with:
          java-version: 17
          distribution: temurin

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        if: steps.skipper.outputs.should_skip != 'true'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        if: steps.skipper.outputs.should_skip != 'true'
        with:
          # Publish dependency graph only for the default branch
          dependency-graph: |
            ${{ (github.event.repository != null && github.ref_name == github.event.repository.default_branch)
            && 'generate-and-submit' || 'disabled' }}

      - name: Build
        if: steps.skipper.outputs.should_skip != 'true'
        run: ./gradlew build coverage

      - name: Publish Test Report
        # Publish test report even if the previous step failed
        if: steps.skipper.outputs.should_skip != 'true' && (success() || failure())
        continue-on-error: true
        uses: dorny/test-reporter@v1
        with:
          name: test report
          path: ./**/build/test-results/test/*.xml
          reporter: java-junit

      - name: Publish Coverage Report
        uses: codecov/codecov-action@v4
        # Publish coverage only for the default branch
        if: |
          steps.skipper.outputs.should_skip != 'true'
          && github.event.repository != null
          && github.ref_name == github.event.repository.default_branch
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_branch: ${{ github.event.workflow_run.head_branch }}
          override_build: ${{ github.event.workflow_run.id }}
          disable_search: true
          files: build/reports/kover/report.xml

      - name: Publish Snapshot
        # Publishing to maven central sometimes fails
        continue-on-error: true
        env:
          VERSION_SUFFIX: ${{ github.ref_name }}-SNAPSHOT
        run: |
          # Remove below line when https://github.com/actions/checkout/issues/1781 is fixed
          git fetch --tags
          declare -r GIT_VERSION="$(git tag -l 'v[0-9]*' --sort=-v:refname | grep -E "^v[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}$" | head -n 1 | cut -c2-)"
          declare -r VERSION=${GIT_VERSION:-0.0.0}
          echo "Simulating snapshot publish to maven central with version: $VERSION_SUFFIX"