name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'gh-pages'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Skip duplicate build on pull_request if pull request uses branch from the same repository
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    steps:
      # Just for debug
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Required to deduce version from git tags
          fetch-depth: 0

      - name: Skip build if not needed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          declare -r PREV_SHA="$(git rev-parse HEAD~1 2>/dev/null || true)"
          if [ "$PREV_SHA" == "HEAD~1" ]; then
            echo "It's an initial commit."
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          declare -r RUNS="$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/runs?head_sha=$PREV_SHA)"
          declare -r BUILD_SUCCESS="$(echo "$RUNS" | jq -r 'limit(1; .workflow_runs[] | select(.name == "Build" and (.conclusion == "success" or .conclusion == "skipped"))) | .conclusion')"
          if [ -z "$BUILD_SUCCESS"  ]; then
            echo "Last commit did not pass Build"
            echo "skip=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          case '${{ github.event_name }}' in
            push)
              SHAS=(${{ join(github.event.commits.*.id, ' ') || 'none' }})
              CHANGED_FILES="$(git diff --name-only --diff-filter=d "${SHAS[0]}~1" "${SHAS[-1]}")"
              ;;
            pull_request)
              CHANGED_FILES="$(git diff --name-only --diff-filter=d '${{ github.event.base_ref }}~1' '${{ github.event.head_ref }}')"
              ;;
          esac
          echo -e "Changed files:\n$CHANGED_FILES"
          NOT_SKIPPED="$(echo "$CHANGED_FILES" \
            | grep -v -e "^[^/]*\.md" -e "^.github/.*\.md" -e "^.gitignore" -e "^docs/.*" -e "^gradle.properties" \
            || echo "")"
          echo -e "\nNot skipped files:\n$NOT_SKIPPED"
          if [ -z "$NOT_SKIPPED" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup JDK
        uses: actions/setup-java@v4
        if: steps.skipper.outputs.skip != 'true'
        with:
          java-version: 21
          distribution: temurin

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        if: steps.skipper.outputs.skip != 'true'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        if: steps.skipper.outputs.skip != 'true'
        with:
          # Publish dependency graph only for the default branch
          dependency-graph: |
            ${{ (github.event.repository != null && github.ref_name == github.event.repository.default_branch)
            && 'generate-and-submit' || 'disabled' }}

      - name: Build
        if: steps.skipper.outputs.skip != 'true'
        run: ./gradlew build coverage

      - name: Publish Coverage Report
        uses: codecov/codecov-action@v4
        # Publish coverage only for the default branch
        if: |
          steps.skipper.outputs.skip != 'true'
          && github.event.repository != null
          && github.ref_name == github.event.repository.default_branch
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_branch: ${{ github.event.workflow_run.head_branch }}
          override_build: ${{ github.event.workflow_run.id }}
          disable_search: true
          files: build/reports/kover/report.xml

      - name: Publish Snapshot
        if: |
          steps.skipper.outputs.skip != 'true'
          && env.GPG_PRIVATE_KEY != ''
          && github.event_name == 'push'
          && (github.ref_name == github.event.repository.default_branch || (startsWith(github.ref_name, 'v') && endsWith(github.ref_name, '.x.x')))
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        # Publishing to maven central sometimes fails
        continue-on-error: true
        run: |
          declare -r GIT_VERSION="$(git tag -l 'v[0-9]*' --merged HEAD --sort=-v:refname | grep -E "^v[0-9]+.[0-9]+.[0-9]+$" | head -n 1 | cut -c2-)"
          declare -r VERSION=${GIT_VERSION:-0.0.0}
          declare -r MAJOR="$(echo "$VERSION" | cut -d. -f1)"
          declare -r MINOR="$(echo "$VERSION" | cut -d. -f2)"
          declare -r PATCH="$(echo "$VERSION" | cut -d. -f3)"
          declare NEXT_VERSION="$MAJOR.$MINOR.$(( PATCH + 1 ))-SNAPSHOT"
          echo "Simulating snapshot publish to maven central with version: $NEXT_VERSION"
          echo "### Published snapshot version $NEXT_VERSION ðŸš€" | tee -a $GITHUB_STEP_SUMMARY
